name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Build aplicação
        run: npm run build

      - name: Iniciar servidor
        run: npx serve -s build -l 3000 &

      - name: Esperar servidor
        run: npx wait-on http://localhost:3000

      - name: Rodar Cypress
        run: npx cypress run